[package]
name = "project"
version = "0.1.0"
edition = "2021"



[dependencies]
actix-web = "4"
web3 = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
bcrypt = "0.15.1"
jsonwebtoken = "9.0.1"
tokio = { version = "1", features = ["full"] }



